# 각 레포지토리의 .github/workflows/close-issues-on-dev-merge.yml

name: Auto Close Issues on dev merge

on:
  pull_request:
    types: [closed]

jobs:
  call-reusable-workflow:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'dev'
    uses: 33-Auto/.github/.github/workflows/reusable-close-linked-issues.yml@main
    # with를 통해 재사용 워크플로우의 inputs에 값을 전달합니다.
    with:
      pr-body: ${{ github.event.pull_request.body }}
      issue-number: ${{ github.event.pull_request.number }}
    secrets: inherit # 재사용 워크플로우가 GITHUB_TOKEN을 사용할 수 있도록 전달